# Основные драйверы
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Поддержка плавающей точки при печати (опционально, код выше использует целочисленное деление)
CONFIG_CBPRINTF_FP_SUPPORT=y

# Увеличение стека системной очереди (Критично для 4x IMU!)
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8096

# Оптимизация SPI (включает асинхронный API, часто помогает на nRF)
CONFIG_SPI_ASYNC=y

# Включение драйвера для семейства LSM6DSV (поддерживает LSM6DSV32X)
CONFIG_LSM6DSV16X=y
CONFIG_LSM6DSV16X_TRIGGER_OWN_THREAD=y

# Логирование (для отладки инициализации сенсора)
CONFIG_LOG=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Thread Analyzer
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5